### ISSUE TITLE
Possible to customize dir structure?

### ISSUE THREAD

**Issue by lee-40square** [jsreport/jsreport-fs-store#13]
Wondering if it's possible to use a deeper nested dir structure. Something like `data/templates/standard templates/invoice/` and `data/templates/custom templates/customer name/invoice`

**Comment by pofider** [comment]
It is on our roadmap to support nested hierarchies in the fs-store, however it is not on the closest features list yet.

**Comment by lee-40square** [comment]
OK. Thanks. By the way, JSReport is one of the best-build systems I have ever worked with. You guys thought of every use case and built it properly without making it overly complicated. Well done!

**Comment by pofider** [comment]
Thanks! Nice motivation for further work.
