### ISSUE TITLE
Entity name with [foo]

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport-fs-store#14]
Example:
Reading an entity [FO]hello
The content file is [FO]hello/content.handlebars
We use [this glob](https://github.com/jsreport/jsreport-fs-store/blob/master/lib/persistence.js#L318) to find the content file, basically want to ignore the file extension using  [FO]hello/content.*.
Unfortunately the [] characters are having a meaning in the glob and the content file is not found then. 

We need to fix the glob somehow.

**Comment by pofider** [comment]
@bjrmatos Please quickly review the linked commit. Thank you

**Comment by bjrmatos** [comment]
@pofider i've made a [comment](https://github.com/jsreport/jsreport-fs-store/commit/cc3f75e25a22f7a11e78a9e9337b15e45adbd214##commitcomment-23848318), other than that, it looks good 👍

**Comment by pofider** [comment]
Thank you for the very true comment. Fixed.

Released in 1.2.2, will be part of the next jsreport hotfix.
