### ISSUE TITLE
Migration from the nedb store

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport-fs-store#2]
We need to provide a migration utility or at least a description somewhere how it can be done manually before this store is set as default in the jsreport

**Comment by omeaart** [comment]
Is there such a description available? I "lost" my templates :/

**Comment by pofider** [comment]
@bjrmatos Is working on migration command line tool, but don't know when it is implemented

If you don't have many templates you can do it manually.
1. Clone (copy paste) jsreport application into two folders
2. Start the first one with the `nedb` in the `connectionString.name` 
3. Start the second one with `fs` in the `connectionString.name`  and with different port than the first one
4. Use  jsreport studio to manually copy paste templates

**Comment by bjrmatos** [comment]
yes! i'm working on this, i'll post here when it is ready :smile:

**Comment by pofider** [comment]
The migration tool is here https://github.com/bjrmatos/jsreport-migrate
Some notes regarding the migration can be found here http://jsreport.net/learn/upgrading-to-10
