### ISSUE TITLE
Initialize socket.io server only in development or with some configuration

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport-fs-store#5]
the socket.io server is handy while developing templates, but using it in production is wasting resources because i don't think that changing a template in jsreport studio should modify the template's file content in an app in production.

also, i think allowing to do modifications to templates in a production app from jsreport studio should be avoided, maybe we can disable modifications to templates through a configuration option in jsreport

**Comment by bjrmatos** [comment]
more context in jsreport/jsreport#142

**Comment by bjrmatos** [comment]
@pofider is ok to you if i send a PR disabling chokidar and socket.io in `production` mode? i think it makes sense to do that in `production`

**Comment by pofider** [comment]
Yes, it makes sense, however the first I need to rethink how we work with the environment modes.

What I don't like, is that the `development` mode is currently enabling usage of unoptimized and unbundled client js files (in new studio it is webpack dev server). I think this is not useful for anybody except the client extensions developers and it is just slowing everybody down. Also, the development mode requires the install from npm without `--production` which makes the app very big. Currently it doesn't make sense to use development mode unless you want to develop jsreport extension. The last, this is not described nor documented.

I'm thinking about the following:
`production` - mode for rendering reports in production, less logs, optimized client files, no socket.io or chokidar (however it should be possible to opt it in)
`development` - mode for developing reports, detailed logs, chokidar and socket.io, optimized client files, should work with `npm install --production`
`jsreport-dev` - mode for developing jsreport extensions, same as development but with webpack dev server

What you think? Would this make more sense?

**Comment by bjrmatos** [comment]
> I'm thinking about the following:
> production - mode for rendering reports in production, less logs, optimized client files, no socket.io or chokidar (however it should be possible to opt it in)
> development - mode for developing reports, detailed logs, chokidar and socket.io, optimized client files, should work with npm install --production
> jsreport-dev - mode for developing jsreport extensions, same as development but with webpack dev server

sounds good and right!

> development - mode for developing reports, detailed logs, chokidar and socket.io, optimized client files, should work with npm install --production

in `development` mode, do you plan to enforce `npm install --production` in some way? or just promote that as a best practice in docs? i think that just picking the optimized build and leave the rest as it is (detailed logs, chokidar and socket.io enabled) in `development` will be the right thing, the matter if the user install the package with `npm install` or `npm install --production` would be an optimization that the user should opt it in, am i missing something?

those are my comments for the dev mode, the rest looks good to me 👍

**Comment by pofider** [comment]
> in development mode, do you plan to enforce npm install --production in some way? 

No enforcement, just recommendation and explanation in docs.

Great! This makes sense to me. Finally the default mode (`development`) will be the most used one. :)

**Comment by bjrmatos** [comment]
cool! i just finished to migrate one application to use `fs-store` but i was worried about chokidar and socket.io enabled in a production server 😂

**Comment by pofider** [comment]
Understand... If you need, I can't introduce there an option to disable that reloading, or if you have it already you can make PR. Just keep the default to the same behavior as now, until I figure out the modes stuff.

**Comment by pofider** [comment]
Released in 0.3.2

**Comment by pofider** [comment]
Thank you

**Comment by pofider** [comment]
Just quick note... For release 1, the default behavior is implemented as the issue originally described. 
- synchronize changes if running in non-production mode
- possible override default using syncModifications option
